### ISSUE TITLE
ladr_to_tptp segfaults

### ISSUE THREAD

**Issue by peoppenheimer** [jessealama/ladr#2]
paul@leonardo:~/Dropbox/ComputationalPhilosophy/OntologicalArgument/1991/prover9
516> ladr_to_tptp < descthm2-direct.in > descthm2-direct.p
Segmentation fault: 11

Here's descthm2-direct.in:

formulas(assumptions).

% Sorting
all x (Object(x) -> -Relation1(x)).
all x all F (Ex1(F,x) -> (Relation1(F) &  Object(x))).
all x all F (Is_the(x,F) -> (Relation1(F) & Object(x))).

% Description Axiom (instance of schema)
all x all F ((Relation1(F) & Object(x)) -> 
  ((Is_the(x,F) & Ex1(F,x)) <-> 
    exists y (Object(y) & Ex1(F,y) &
      all u (Ex1(F,u) -> u=y) & Ex1(F,y)))).

end_of_list.

formulas(goals).

all F (Relation1(F) -> ((exists y (Object(y) & Is_the(y,F))) -> (all z (Object(z) -> (Is_the(z,F) -> Ex1(F,z)))))).

end_of_list.

**Comment by jessealama** [comment]
$ ladr_to_tptp < paul.in 

% The LADR formulas contain function or predicate symbols
% that are not legal TPTP symbols, and we have replaced those
% symbols with new symbols.  Here is the list of the unaccepted
% symbols and the corresponding replacements.
%
%   (arity 2)      Ex1    tptp0
%   (arity 2)   Is_the    tptp1
%   (arity 1)   Object    tptp2
%   (arity 1) Relation1    tptp3

fof(sos,axiom,! [X0] : (tptp2(X0) => ~ tptp3(X0))).
fof(sos,axiom,! [X1] : ! [X2] : (tptp0(X2,X1) => (tptp3(X2) & tptp2(X1)))).
fof(sos,axiom,! [X3] : ! [X4] : (tptp1(X3,X4) => (tptp3(X4) & tptp2(X3)))).
fof(sos,axiom,! [X5] : ! [X6] : ((tptp3(X6) & tptp2(X5)) => ((tptp1(X5,X6) & tptp0(X6,X5)) <=> ? [X7] : (tptp2(X7) & (tptp0(X6,X7) & (! [X8] : (tptp0(X6,X8) => X8 = X7) & tptp0(X6,X7))))))).
fof(goals,conjecture,! [X9] : (tptp3(X9) => (? [X10] : (tptp2(X10) & tptp1(X10,X9)) => ! [X11] : (tptp2(X11) => (tptp1(X11,X9) => tptp0(X9,X11)))))).

**Comment by peoppenheimer** [comment]
$ cat descthm2-direct.in 
formulas(assumptions).

% Sorting
all x (Object(x) -> -Relation1(x)).
all x all F (Ex1(F,x) -> (Relation1(F) &  Object(x))).
all x all F (Is_the(x,F) -> (Relation1(F) & Object(x))).

% Description Axiom (instance of schema)
all x all F ((Relation1(F) & Object(x)) -> 
  ((Is_the(x,F) & Ex1(F,x)) <-> 
    exists y (Object(y) & Ex1(F,y) &
      all u (Object(u) -> (Ex1(F,u) -> u=y))))).
end_of_list.

formulas(goals).

% Description Theorem 2 (instance of schema)
(all F (Relation1(F) -> 
     ((exists x (Object(x) & Is_the(x,F))) -> 
       (all y (Object(y) -> 
         (Is_the(y,F) -> Ex1(F,y)))))))
end_of_list.

$ ladr_to_tptp < descthm2-direct.in 
Segmentation fault: 11

**Comment by jessealama** [comment]
Are you sure you're using the latest version? Does this version also crash on the LADR file that was causing ladr_to_tptp to crash a while ago?

**Comment by peoppenheimer** [comment]
Not all the search paths for executables on my machine were set up correctly.

I'm closing the issue.

Thanks!
